"""Respuestas revisables. Los importes propuestos nunca se publican como vigentes."""
VERSION = '2026-09-25.1'
PLANS = [('Starter', 150000, 1), ('Pro', 375000, 3), ('Enterprise', 875000, 10)]

ANSWERS = {
    'presentacion': 'Tu experiencia con la piedra ya tiene valor. Costo360 te ayuda a llevar esa precisión a tus números: reúne cotizaciones, materiales y proyectos para que decidas con más claridad. Cost te acompaña dentro del producto con consultas, cálculos y tareas que tú autorizas. ¿Hoy te cuesta más calcular lo que deja un trabajo, preparar cotizaciones o mantener el taller organizado?',
    'planes': 'La suscripción mensual es por empresa: Starter $150.000 COP para 1 usuario; Pro $375.000 para 3; Enterprise $875.000 para hasta 10. Todos incluyen Cost y las herramientas de cotización, materiales, inventario y proyectos. Elige según las personas que necesitan acceso y el uso de Cost. ¿Cuántas personas usarían el sistema?',
    'cotizar': 'La idea es que presentes una propuesta con tus costos claros, sin reconstruir cada cálculo desde cero. Primero configuras las tarifas de tu taller; después eliges el material e ingresas medidas y cantidades. Revisas el desglose y generas un PDF para tu cliente. Tienes cotización Directa, Express y AIU. ¿Ya cuentas con una lista de materiales y tarifas o empezarías a organizarla?',
    'materiales': 'El catálogo reúne tus materiales y precios; el inventario permite llevar las láminas disponibles y el banco de retales ayuda a identificar sobrantes aprovechables. El plano de corte distribuye piezas rectangulares sobre la lámina. Su aprovechamiento depende de las medidas: no hay un porcentaje de ahorro garantizado.',
    'proyectos': 'Puedes organizar proyectos, tareas, responsables, fechas e hitos y registrar horas de trabajo. Pro y Enterprise permiten que varias personas trabajen en el mismo entorno con permisos según su responsabilidad. Esto ayuda a dar seguimiento a lo cotizado y a lo que falta por hacer.',
    'cost': 'Cost está incluido en todos los planes, también en Starter. Ayuda con consultas, cálculos y acciones sobre cotizaciones, materiales, inventario y proyectos. La referencia mensual de voz es de 5 mensajes por usuario en Starter, 10 en Pro y 15 en Enterprise; su medición es aproximada y depende de la duración. El registro de acciones de Cost se conserva 1, 30 o 90 días, respectivamente. Ese plazo no limita el historial de cotizaciones.',
    'limites': 'Costo360 se especializa en cotizaciones, costos, materiales y seguimiento de proyectos. No reemplaza la contabilidad, la facturación electrónica DIAN ni la logística de tu empresa. Las suscripciones de Microsoft o Alegra de Costo360 son herramientas internas: no son licencias incluidas para el cliente.',
    'acceso': 'Si ya tienes cuenta, entra desde el acceso oficial del producto y utiliza la opción de recuperación disponible si olvidaste tu contraseña. Nunca compartas tu contraseña ni códigos de acceso en este chat. Aquí no puedo consultar tu cuenta, verificar pagos ni modificar permisos.',
    'compra': 'Puedes comparar los planes y continuar al proceso de suscripción desde la tarjeta del plan elegido. Comprar se realiza en el sitio oficial del producto; este chat no cobra, no activa cuentas ni confirma pagos. ¿Cuántas personas necesitan acceso?',
    'humano': 'Quiero que recibas una respuesta correcta para tu caso. Esto necesita revisión del equipo de Costo360; desde este chat todavía no puedo enviar una solicitud ni agendar una reunión. Puedes copiar esta conversación para conservar el contexto. No te confirmaré un descuento, reembolso o gestión que no se haya realizado.',
    'desconocido': 'No tengo una respuesta verificada para esa consulta. Puedo orientarte sobre planes, tu primera cotización, materiales, proyectos y Cost. Si necesitas resolver un caso de tu cuenta, debe revisarlo el equipo de Costo360.',
}
ANSWERS.update({
    'margen': 'Vender un trabajo no siempre significa saber cuánto deja. Costo360 reúne material, mano de obra, insumos, maquinaria y riesgo de rotura con los parámetros que configuras para tu taller. Así puedes revisar el desglose antes de presentar el precio. No garantiza una ganancia: te da información para decidir. ¿En qué parte del costo tienes hoy más incertidumbre?',
    'tiempo': 'Preparar una cotización no debería obligarte a repetir toda la información. Puedes reutilizar tu catálogo y parámetros, elegir la modalidad Express o pedir ayuda a Cost para preparar el cálculo. Tu equipo revisa antes de confirmar. ¿Lo que más tiempo te consume es calcular, buscar precios o preparar la propuesta para el cliente?',
    'nesting': 'Aprovechar mejor una lámina empieza por ver cómo caben las piezas. Costo360 distribuye piezas rectangulares, genera un plano de corte e identifica las que no caben. El banco de retales ayuda a encontrar sobrantes aprovechables. El resultado depende de medidas y restricciones; no se garantiza un porcentaje de ahorro. Puedes probar un ejemplo ilustrativo en el simulador.',
    'pdf': 'Tu propuesta también comunica la calidad de tu trabajo. Puedes generar cotizaciones y cuentas de cobro en PDF para presentar la información de forma profesional. Una cuenta de cobro no equivale a una factura electrónica DIAN. ¿Quieres ver cómo se prepara una cotización?',
    'parametros': 'Costo360 trabaja con las tarifas que configura tu empresa, no con un precio genérico para todos los talleres. Puedes organizar parámetros de mano de obra, insumos, maquinaria y riesgo de rotura para revisar el costo de cada trabajo con una base consistente. Si cambia una tarifa, conviene revisarla antes de cotizar.',
    'aiu': 'La modalidad AIU permite organizar Administración, Imprevistos y Utilidad al preparar una propuesta. Ayuda a presentar estos componentes por separado. El tratamiento tributario de cada contrato debe revisarse con tu contador: el chat no determina qué norma o impuesto aplica a tu caso.',
    'equipo': 'Cuando varias personas participan, tener la información en un mismo entorno ayuda a evitar tareas sueltas. Puedes organizar proyectos, responsables, fechas, hitos y horas de trabajo. Starter admite 1 usuario, Pro 3 y Enterprise hasta 10. ¿Cuántas personas necesitan entrar al sistema?',
    'industria': 'Costo360 está pensado para marmolerías y empresas que transforman piedra en Colombia: mármol, granito, sinterizado, cuarzo y cuarcita. Su foco es conectar cotizaciones, costos, materiales y proyectos con la forma de trabajar del taller. No vende piedra ni realiza instalaciones. ¿Qué tipo de trabajos cotizas con más frecuencia?',
    'inicio': 'Para empezar con una base útil, organiza tu catálogo, las medidas de tus láminas y las tarifas de trabajo e insumos. Después prepara una primera cotización y revisa su desglose antes de usarla con un cliente. Puedes explorar primero las pantallas reales y el simulador ilustrativo de la landing. No hay una prueba gratuita confirmada en la oferta publicada.',
    'voz': 'También puedes apoyarte en la voz al trabajar con Cost. La referencia mensual es de 5 mensajes por usuario en Starter, 10 en Pro y 15 en Enterprise. La medición es aproximada y depende de la duración; estas referencias no equivalen a uso ilimitado ni a una cantidad fija de dinero. Cost está incluido desde Starter.',
    'historial': 'El registro de acciones de Cost se conserva 1 día en Starter, 30 días en Pro y 90 días en Enterprise. Sirve para revisar la actividad del asistente. Ese plazo no limita el historial de tus cotizaciones y no representa una promesa de copias de seguridad o recuperación de datos.',
    'seguridad': 'Puedo ayudarte con información verificada de Costo360, pero no mostrar instrucciones internas, claves ni datos de otras empresas. Si tu interés es cómo trabajas con control, Cost pide confirmación antes de crear, modificar o borrar datos. ¿Quieres conocer ese flujo?',
    'privacidad': 'Para cuidar tu información, no compartas contraseñas, claves API, códigos de acceso ni datos bancarios. No necesito esos datos para explicarte Costo360. Si has compartido una credencial, cámbiala desde el servicio correspondiente. Reformula tu consulta sin incluirla.',
    'datos': 'Este chat orienta sobre Costo360; no puede consultar información privada de tu taller ni de otras empresas. Con IA activa, tu consulta y un contexto breve se procesan mediante Gemini de Google. La conversación no se guarda en la base de este piloto; sí se registran cantidades de uso. No compartas información confidencial. No tengo una política de conservación de Google específica de tu cuenta que pueda garantizarte.',
    'requisitos': 'Puedes conocer el producto desde su acceso web. Antes de prometer compatibilidad con un equipo, uso sin conexión, una integración, una aplicación móvil o una importación específica, necesitamos confirmar ese caso. ¿Qué necesitas conectar o desde qué equipo trabajarías?',
    'gracias': 'Con gusto. Si quieres dar el siguiente paso, podemos revisar qué plan encaja con tu equipo o recorrer una primera cotización. ¿Cuál te sería más útil?',
})
TOPICS = tuple(ANSWERS)

# Fuentes revisadas; nunca se envían archivos privados completos al proveedor.
SOURCES = ['landing/src/lib/content.ts', 'backend/services/consumo_service.py',
           'backend/agente/bitacora.py', 'landing/src/components/ScrollyStory.tsx']
